[build-system]
requires = ["hatchling", "pip==25.0", "setuptools==70.0"]
build-backend = "hatchling.build"


[project]
name = "solace_ai_connector"
dynamic = ["version"]
authors = [
  { name="Edward Funnekotter", email="edward.funnekotter@solace.com" },
]
description = "Solace AI Connector - make it easy to connect Solace PubSub+ Event Brokers to AI/ML frameworks"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "PyYAML==6.0.2",
    "Requests==2.32.3",
    "solace_pubsubplus==1.9.0",
    "SQLAlchemy==2.0.40",
    'pywin32>=306; sys_platform == "win32"',
]

[project.optional-dependencies]
# Basic LLM functionality
llm = [
    "litellm==1.61.20",
    "waitress==2.1.2",
    "Flask-WTF==1.2.2",
]

# OpenAI specific dependencies
openai = [
    "openai==1.64.0",
    "langchain-openai==0.3.8",
]

# AWS integration (Bedrock, etc.)
aws = [
    "langchain_aws==0.2.7",
    "requests_aws4auth>=1.3.1",
]

# Vector stores
chromadb-vector-store = [
    "boto3==1.34.162",
    "chromadb==0.6.3",
    "langchain-chroma==0.2.2",
]

qdrant-vector-store = [
    "boto3==1.34.162",
    "langchain-qdrant==0.2.0",
    "qdrant-client==1.10.1",
]

milvus-vector-store = [
    "boto3==1.34.162",
    "langchain_milvus==0.1.8",
    "pymilvus==2.5.6",
]

# PostgreSQL vector database
pgvector = [
    "boto3==1.34.162",
    "pgvector==0.3.6",
    "langchain-postgres==0.0.13",
]

# LangChain core and utilities
langchain = [
    "langchain==0.3.21",
    "langchain-text-splitters==0.3.7",
]

# Web search capabilities
websearch = [
    "duckduckgo-search==7.5.5",
    "google-api-python-client==2.166.0",
]

# Web scraping
webscraping = [
    "playwright==1.51.0",
    "beautifulsoup4==4.13.3",
]

# RAG (Retrieval Augmented Generation)
rag = [
    "boto3==1.34.162",
    "litellm==1.61.20",
    "waitress==2.1.2",
    "Flask-WTF==1.2.2",
    "langchain-qdrant==0.2.0",
    "langchain-text-splitters==0.3.7",
    "openai==1.64.0",
    "langchain-openai==0.3.8",
]

# Mongo database
mongodb = [
    "pymongo==4.10.1",
]

# All dependencies
all = [
    # From llm
    "litellm==1.61.20",
    "waitress==2.1.2", 
    "Flask-WTF==1.2.2",
    
    # From openai
    "openai==1.64.0",
    "langchain-openai==0.3.8",
    
    # From aws
    "langchain_aws==0.2.7",
    "requests_aws4auth==1.3.1",
    
    # From vector-stores
    "boto3==1.34.162",
    "chromadb==0.6.3",
    "langchain-chroma==0.2.2",
    "langchain-qdrant==0.2.0",
    "qdrant-client==1.10.1",
    "langchain_milvus==0.1.8",
    "pymilvus==2.5.6",
    
    # From pgvector
    "pgvector==0.3.6",
    "langchain-postgres==0.0.13",
    
    # From langchain
    "langchain==0.3.21",
    "langchain-text-splitters==0.3.7",
    
    # From websearch
    "duckduckgo-search==7.5.5",
    "google-api-python-client==2.166.0",
    
    # From webscraping
    "playwright==1.51.0",
    "beautifulsoup4==4.13.3",

    # Mongo database
    "pymongo==4.10.1",
]


[project.urls]
homepage = "https://github.com/SolaceLabs/solace-ai-connector"
repository = "https://github.com/SolaceLabs/solace-ai-connector"
documentation = "https://github.com/SolaceLabs/solace-ai-connector/blob/main/docs/index.md"


[project.scripts]
solace-ai-connector = "solace_ai_connector.main:main"
solace-ai-connector-gen-docs = "solace_ai_connector.tools.gen_component_docs:main"

[tool.hatch.envs.hatch-test]
installer = "pip"
dependencies = [
    "pip==25.0",
    "setuptools==70.0"
]

# Specify minimum and maximum Python versions to test
[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12"]

[tool.hatch.build.targets.wheel]
packages = ["src/solace_ai_connector"]

[tool.hatch.version]
path = "src/solace_ai_connector/__init__.py"

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F"]
lint.ignore = ["F401", "E731"]
