name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: "Version bump type"
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  checks: write

jobs:
  release:
    uses: SolaceDev/solace-public-workflows/.github/workflows/hatch_release_pypi.yml@v1.0.0
    with:
      version: ${{ github.event.inputs.version }}
      pypi-project: solace-ai-connector
    secrets:
      COMMIT_KEY: ${{ secrets.COMMIT_KEY }}
